### ISSUE TITLE
Number of devices limited to ~110

### ISSUE THREAD

**Issue by jenskastensson** [actions-on-google/actionssdk-smart-home-nodejs#60]
I'm able to SYNC 150 devices and they are listed in the iOS Home app. However I cannot operate any device the EXECUTE action never reaches the server. When I reduce the number of devices to 110 it works again. How can I troubleshoot this? I have lights and thermostats, realKNX service (live).

**Comment by Fleker** [comment]
Are these 150 devices for one Smart Home provider, or all of them?

**Comment by jenskastensson** [comment]
If the definition of a "Smart Home provider" is an Action on Google implemented as a NodeJs server, the answer is yes.  (..what do you mean with 'all of them'?)

**Comment by jenskastensson** [comment]
If it helps I can setup a test system (and provide a credentials)  so you can link to our service?

**Comment by Fleker** [comment]
If you [add me](mailto:fleker@google.com) to the project I will be able to test it out. Are you returning a single JSON payload or is there some sort of timeout which may be happening on the Assistant server side?

**Comment by jenskastensson** [comment]
You're already added PID: bubble-talk-34ebf
Yes I'm returning a single JSON payload, no timeout during SYNC as far as I
could see.

**Comment by Fleker** [comment]
Are you just trying to execute single devices, or have you grouped them into rooms and trying to execute those?

**Comment by jenskastensson** [comment]
No commands at all will reach the server. Not even the most simple one
"turn on bedroom ceiling"

On 17 Nov 2017 19:50, "Nick" <notifications@github.com> wrote:

Are you just trying to execute single devices, or have you grouped them
into rooms and trying to execute those?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/actions-on-google/actionssdk-smart-home-nodejs/issues/60#issuecomment-345330929>,
or mute the thread

**Comment by Fleker** [comment]
Do you see any errors in your server? Does the Google Assistant give any errors?

**Comment by jenskastensson** [comment]
No errors during  the sync (I haven't yet tested the Json with the new
tool, will do that next week)

**Comment by Fleker** [comment]
When you try to turn on a device, what happens to the command?

**Comment by jenskastensson** [comment]
Nothing on the server side. I don't get the call.

**Comment by Fleker** [comment]
When you tell the Google Assistant "turn on bedroom ceiling" how does it respond?

**Comment by jenskastensson** [comment]
Sorry I can't recall but it was an error message.

**Comment by Fleker** [comment]
If you can get an error message or a video it'd help, although I'll check out what's happening on the server.

**Comment by jenskastensson** [comment]
Thx I will provide more info Monday. Do you need remote access to the 150
devices?

**Comment by Fleker** [comment]
If you can add my account to the project I'll be able to check it out.

**Comment by jenskastensson** [comment]
A summary if someone else have a similar problem:

1. The original issue 110 devices limit was most likely sync data problem (fixed with the help of the SYNC data validator tool).  **fixed*

2. When I sync the 150 devices, it always fails the first time. No devices appear in the list, even if I wait and update. Then the second time, the devices appear after an error message and refresh.
 ---->**open** Fleker to test in the simulator (see Issue 4 and mai with title "Number of devices limited to ~110 (#60)")

 3. The Action was certified and released [test] removed icon added-  but the status in console was 'Under review', 
 -> **fixed**, the status is now "Published"

4. Enabling Testing from the simulator is not possible after release.  When the simulator is opened and mouse hover over the test icon the message "Testing on device: Active" is shown.  If "Test this version" is selected from the list of versions, the error message Test in simulator is not possible.  Maybe I have misunderstood something but it is a bit unclear.

**Comment by Fleker** [comment]
I think the simulator issue is unrelated.

**Comment by jenskastensson** [comment]
Agree but it stops you from testing..

**Comment by jenskastensson** [comment]
I tested the simulator once more and it works now ,can you test the  with
the info below:

Can you try to link and see if it works for you?
uname: fleker@google.com
pswd: z4QU3sZ5

**Comment by Fleker** [comment]
I still can't simulate on the draft version. Are you using a different version?

Has the original issue been resolved for you?

**Comment by jenskastensson** [comment]
Nick, you can't use the simulator for our project as it is published, see
message from umairmuhammad@google.com below

The original title issue is resolved. I will close this a reopen when I
have collected more information (error message after SYNC on some devices)

From umairmuhammad@google.com
I believe ones a project is launched into production, you may not be able
to see the project the same way for testing.
If you intent on testing new functionality that you intent to add to your
existing launched project then I would recommend that you create a DEV/TEST
project and test it unlaunched.
